### PR TITLE
[infra] update_columns | create tests | windows encoding

### PR DESCRIPTION
**Pull request by d116626**

### CODE REVIEW

**Comment by d116626** [comment]
image

**Comment by d116626** [comment]
image

**Comment by d116626** [comment]
@mavalentim, manda aquele erro la pff

**Comment by JoaoCarabetta** [comment]
[Integrar columns_config.csv no table_config.yaml via Python](https://trello.com/c/LgtP5XJw/67-integrar-columnsconfigcsv-no-tableconfigyaml-via-python)

**Comment by d116626** [comment]
RESOLVIDO NO PR #675!!!

**Pull request closed without merging**
